M48
; DRILL file {KiCad 8.0.1} date 2024-04-10T11:02:09-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-10T11:02:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X3.307Y-5.227
X4.6654Y-3.2855
X7.2441Y-3.2874
X8.6024Y-5.2264
M30
